# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:

  ci:

    runs-on: ubuntu-latest #TODO cambiare con donatello

    steps:
      - name: Github Pull Request
        run: git pull #TODO: pull from repository

      - name: Launch HLS
        run: echo Hello, world! #TODO: launch HLS

      - name: Launch Vivado
        run: echo vivado #TODO: launch Vivado
        
      - name: Synthethis Project
        run: echo vivado #TODO: Synthethis Project
      
      - name: Transfer Bitstream and release 
        run: echo vivado #TODO: 
      
      - name: Launch Test
        run: echo vivado #TODO:
      
      - name: Execution Time Log 
        run: echo vivado #TODO:
